[features]
seeds = false
[programs.mainnet]
staking = "85SU7o78xMPtVVKPsVb4msfgw7foc3D4rtzTi9rSvqub"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
